spring:
  datasource:
    url: 'jdbc:mysql://db:3306/PeakLogistics'
#    url: 'jdbc:mysql://localhost:3306/PeakLogistics'
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    default-schema: PeakLogistics
    baseline-on-migrate: true